In [11]:
import numpy as np

# from IntersectionPoint import intersection_point
# %run IntersectionPoint.py

from IntersectionPolygons import intersection_polygon_by_edge
%run IntersectionPolygons.py

from classes import Vertex

item = np.array([Vertex(np.array([1,0]), np.array([[1,2], [0,0]])),
        Vertex(np.array([1,2]), np.array([[2,2], [0,0]])),
        Vertex(np.array([2,2]), np.array([[2,0], [0,0]])),
        Vertex(np.array([2,0]), np.array([[1,0], [0,0]]))])

edge = Vertex(np.array([0,1]), np.array([[3,1], [0,0]]))

In [12]:
intersection_polygon_by_edge(item, edge)

[[1 0]
 [1 2]] --- [[0 1]
 [3 1]]
тут
[[1 2]
 [2 2]] --- [[0 1]
 [3 1]]
[[2 2]
 [2 0]] --- [[0 1]
 [3 1]]
тут
[[2 0]
 [1 0]] --- [[0 1]
 [3 1]]


[[1.0, 1.0], [2.0, 1.0]]